// <auto-generated />
using System;
using Infra.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.Migrations
{
    [DbContext(typeof(MySqlContext))]
    partial class MySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Produtos.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Fabricacao");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Domain.Produtos.Produto", b =>
                {
                    b.OwnsOne("Domain.Produtos.ValueObjects.Dinheiro", "Valor", b1 =>
                        {
                            b1.Property<Guid?>("ProdutoId");

                            b1.Property<decimal>("Valor")
                                .HasColumnName("Valor");

                            b1.ToTable("Produtos");

                            b1.HasOne("Domain.Produtos.Produto")
                                .WithOne("Valor")
                                .HasForeignKey("Domain.Produtos.ValueObjects.Dinheiro", "ProdutoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Domain.Produtos.ValueObjects.Tamanho", "Tamanho", b1 =>
                        {
                            b1.Property<Guid?>("ProdutoId");

                            b1.Property<string>("Tamanho")
                                .HasColumnName("Tamanho");

                            b1.ToTable("Produtos");

                            b1.HasOne("Domain.Produtos.Produto")
                                .WithOne("Tamanho")
                                .HasForeignKey("Domain.Produtos.ValueObjects.Tamanho", "ProdutoId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
